server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.122.129:8848
      discovery:
        namespace: 0d663d31-a634-46a0-84dd-5b799be08930
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: department
          uri: lb://department-service
          predicates:
            - Path=/department/**


jwt:
  secureKey: ${jwt.secureKey}
  expire: ${jwt.expire}

auth:
  excludePaths:
    ${auth.excludePaths}
  includePaths:
    ${auth.includePaths}